Sync with GE preset
osmlab/name-suggestion-index pull request #10235
Opened 2024-12-19 09:38 UTC by balsoft

Syncs with https://github.com/komachi/josm-ge-preset, mostly adding wikidata tags

2024-12-19 10:06 UTC, Cj-Malone requested changes
Having a quick glance, the biggest thing is `operator:wikidata` without `operator`. But also I don't think we should be encouraging `operator:wikidata` to be a copy of `brand:wikidata`.

2024-12-19 11:04 UTC, balsoft commented
@Cj-Malone done, please squash before merging though

2024-12-23 07:52 UTC, balsoft commented
@Snowysauce agreed on both counts, fixed.

2025-01-01 10:15 UTC, Cj-Malone approved these changes
I'm not to fond of some of this, removing `name`, flip flopping on `payment:*`, adding `operator` which is the same as `brand`. However, lets go for now.

2025-01-01 10:17 UTC, merged