#4121 Added Cibo Espresso to amenity/cafe
osmlab/name-suggestion-index pull request #4157
Opened 2020-09-17 12:09 UTC by ParthoShuvo

2020-09-17 12:33 UTC, bhousel commented on brands/amenity/cafe.json
> +        "brand:wikipedia": "en:Cibo Espress",
```suggestion
        "brand:wikipedia": "en:Cibo Espresso",
```

2020-09-17 12:34 UTC, bhousel requested changes
Welcome @ParthoShuvo  👋 
Looks mostly good - just one minor issue to fix before we can merge it..

2020-09-17 13:00 UTC, ParthoShuvo commented
Hi @bhousel,

Please review the changes.

Thanks.

2020-09-18 12:42 UTC, bhousel approved these changes

2020-09-18 12:42 UTC, bhousel commented
Looks good @ParthoShuvo , thanks for the quick fix!

2020-09-18 12:42 UTC, merged