add 'Cruz Roja' wikidata & wikipedia
osmlab/name-suggestion-index pull request #4520
Opened 2020-10-17 19:37 UTC by adrcav

I added wikidata and wikipedia data for Cruz Roja in brands/amenity/hospital.

2020-10-17 19:54 UTC, Binnette commented on data/brands/amenity/hospital.json
> +      "locationSet": {"include": ["ch"]},
Hi. "ch" stands for Switzerland. You should replace "ch" by "es". "es" stands for Spain. 

Details : https://en.wikipedia.org/wiki/List_of_countries_by_United_Nations_geoscheme

2020-10-17 20:02 UTC, Binnette requested changes
Hello

2020-10-17 20:02 UTC, Binnette commented on data/brands/amenity/hospital.json
> +      "locationSet": {"include": ["ch"]},
And BTW "ch" is Switzerland ;)

2020-10-17 20:23 UTC, adrcav commented on data/brands/amenity/hospital.json
> +      "locationSet": {"include": ["ch"]},
Yes, you're right. I've updated it.

2020-10-18 13:46 UTC, UKChris-osm commented
If "_Cruz Roja_" is Spanish for "_Red Cross_" would it be better to target the locationSet to Spanish speaking countires?

2020-10-18 15:28 UTC, bhousel requested changes
> If "_Cruz Roja_" is Spanish for "_Red Cross_" would it be better to target the locationSet to Spanish speaking countires?

I agree we don't want _Cruz Roja_ worldwide.  Just include the parts of the world where it is called that.

2020-10-21 13:06 UTC, bhousel approved these changes

2020-10-21 13:06 UTC, bhousel commented
Thanks @adrcav , looks good 👍

2020-10-21 13:06 UTC, merged