Split Provinzial into two companies
osmlab/name-suggestion-index pull request #4548
Opened 2020-10-20 20:18 UTC by tordans

Fixes https://github.com/osmlab/name-suggestion-index/issues/4544

I left the id-values empty, see https://github.com/osmlab/name-suggestion-index/issues/4547.

2020-10-21 11:22 UTC, tordans commented
Question: When I ran the build-script, the script re-added the previous data again. I dont know where that came from, since I removed it (twice). I did not commit the previous data, just the new one. Should I?

2020-10-21 13:25 UTC, bhousel requested changes
Thanks @tordans , looks mostly good!
The wikidata tags need underscores replaced with spaces, then good to merge..

2020-10-21 13:25 UTC, bhousel commented on data/brands/office/insurance.json
> +        "brand:wikipedia": "de:Provinzial_NordWest",
```suggestion
        "brand:wikipedia": "de:Provinzial NordWest",
```

2020-10-21 13:25 UTC, bhousel commented on data/brands/office/insurance.json
> +        "brand:wikipedia": "de:Provinzial_Rheinland",
```suggestion
        "brand:wikipedia": "de:Provinzial Rheinland",
```

2020-10-21 19:22 UTC, tordans commented
> The wikidata tags need underscores replaced with spaces, then good to merge..

@bhousel thank for the change-suggestions, I commited them.
Where would I normally copy this string from? Is it the title of the wikipedia-doc prefixed with the lang?

2020-10-21 21:15 UTC, Identitaet commented
You'll find the language code at the begging of the Wikipedia link something like 
`www.en.wikpedia and so on`
And the non encoded version of the name will be in the top left as the title

2020-10-22 13:53 UTC, bhousel approved these changes

2020-10-22 13:53 UTC, merged