#4231 Complete some records in transit/route/bus + transit/route/ferry
osmlab/name-suggestion-index pull request #4551
Opened 2020-10-21 10:22 UTC by Tck13

U > AggloBus
U > Aguia Branca
U > AIM Mobilità
M > Ålandstrafiken (it's a ferry company)
U > Álava Bus
U > Albatrans

U = updated
M = moved

2020-10-21 13:39 UTC, bhousel requested changes
> M > Ålandstrafiken (it's a ferry company)

It looks like it operates both ferries and busses:
https://overpass-turbo.eu/s/Zg6
Can you restore the Ålandstrafiken item in the bus.json file?  (Keeping it in ferry.json is good)

2020-10-21 20:28 UTC, Tck13 commented
> Can you restore the Ålandstrafiken item in the bus.json file? (Keeping it in ferry.json is good)

Above commit restores `Ålandstrafiken` as a bus operator

2020-10-22 13:56 UTC, bhousel approved these changes

2020-10-22 13:56 UTC, merged

2020-10-22 13:56 UTC, bhousel commented
Thanks @Tck13 👍