Add Econsave mini market branch
osmlab/name-suggestion-index pull request #5100
Opened 2021-05-29 14:42 UTC by MASangys

see https://econsave.com.my/all-stores/

2021-05-29 14:44 UTC, bhousel commented on data/brands/shop/variety_store.json
> +        "brand:wikidata": "Q61776108",
https://www.wikidata.org/wiki/Q61776108 looks wrong - it goes to something unrelated?

2021-05-29 14:45 UTC, bhousel requested changes
Q61776108 wrong

2021-05-29 14:51 UTC, MASangys commented
Q61776608

2021-06-01 21:02 UTC, MASangys commented
Hello, any update?

2021-06-01 21:41 UTC, bhousel approved these changes

2021-06-01 21:41 UTC, merged

2021-06-01 21:42 UTC, bhousel commented
> Hello, any update?

Thanks, looks fine now.. We had a holiday here and I wasn't paying much attention for the past few days.