Add Taiwan local food chain
osmlab/name-suggestion-index pull request #5264
Opened 2021-08-22 17:47 UTC by Supaplextw

fix some localized food chain to Taiwan traditional Chinese character

2021-08-22 18:30 UTC, arch0345 requested changes
Looks good, just change the Wikipedia for Saizeriya to the chinese wikipedia and add "brand:wikidata" tags to "梁社漢排骨". If it doesn't have one yet, you could easily add one. Make sure to include their Facebook and/or Twitter username in the page if they have one to help display the logo.

2021-08-22 18:30 UTC, arch0345 commented on data/brands/amenity/restaurant.json
> +        "brand:wikipedia": "en:Saizeriya",
This could be "zh:萨莉亚" instead

2021-08-22 18:30 UTC, arch0345 commented on data/brands/amenity/restaurant.json
> +        "brand:en": "Liang She Han Buy Food",
There aren't any "brand:wikidata" tags for this brand

2021-08-23 02:37 UTC, Supaplextw commented on data/brands/amenity/restaurant.json
> +        "brand:en": "Liang She Han Buy Food",
I'll add the Wikidata item for 梁社難排骨

2021-08-23 02:46 UTC, LaoshuBaby commented on data/brands/amenity/restaurant.json
> +        "include": ["tw"]
in Line 2789, it include 5 country/region: ```"include": ["ae", "eg", "qa", "tw", "us"]```

if you create a new item that suitable for ```"tw"```, you'd better remove it from the list next time.

I'll fix this.

2021-08-23 02:51 UTC, LaoshuBaby commented on data/brands/amenity/restaurant.json
> +        "include": ["tw"]
Fixed in https://github.com/osmlab/name-suggestion-index/pull/5264/commits/45ad37552569889e78dc761ca9a77405814c59a9

2021-08-23 02:51 UTC, LaoshuBaby commented on data/brands/amenity/restaurant.json
> +        "brand:en": "Liang She Han Buy Food",
Fixed in https://github.com/osmlab/name-suggestion-index/pull/5264/commits/45ad37552569889e78dc761ca9a77405814c59a9

2021-08-23 02:54 UTC, LaoshuBaby commented on data/brands/amenity/restaurant.json
> +        "include": ["ae", "eg", "qa", "tw", "us"]
this will cause you find 2 item when you tag, one named ```Ponderosa Steakhouse```, and another named ```龐德羅莎``` (at L2805)

2021-08-23 02:54 UTC, Supaplextw reviewed
add 梁社漢 wikidata item

2021-08-23 02:59 UTC, LaoshuBaby commented
> 
> 
> add 梁社漢 wikidata item

![图片](https://user-images.githubusercontent.com/42690037/130383993-1fa97888-f719-44c8-9ae3-0ff786f69c28.png)

![图片](https://user-images.githubusercontent.com/42690037/130384006-56d155b0-c862-414d-a833-a6d391e6c043.png)

Oops, maybe I wrong used this

2021-08-23 02:59 UTC, arch0345 approved these changes

2021-08-23 03:01 UTC, arch0345 commented
It looks like you two added Wikidata entries so I merged them. All issues have been resolved so I'll merge this

2021-08-23 03:01 UTC, LaoshuBaby approved these changes

2021-08-23 03:01 UTC, merged

2021-08-23 03:03 UTC, LaoshuBaby commented
> 
> 
> It looks like you two added Wikidata entries so I merged them. All issues have been resolved so I'll merge this

OK ,if @Supaplextw have idea between "梁社難" or "梁社漢", he can edit on wikidata to ensure it meet the fact.