Added 3 tunisian restaurants
osmlab/name-suggestion-index pull request #5730
Opened 2021-11-24 20:11 UTC by eddy-dardour

Hi I am new to GitHub and also new to OpenSource, I tried to add three restaurants in the restaurant.json file. Comment if I made a mistake, I am not very experienced.

2021-11-24 20:22 UTC, arch0345 commented
Thanks and welcome to the NSI community! It looks like you added a file in the parent directory - is it possible for you to add these to the existing file in another PR (`data/brands/amenity/restaurant.json`)? To edit it, just click on the pencil icon. If you need any help feel free to respond

2021-11-24 20:43 UTC, eddy-dardour commented
I don't really get what you mean. I actually just changed the json file.

2021-11-24 23:56 UTC, arch0345 commented
The file should be in the appropriate folder within the data folder (in this case `data/brands/amenity`) instead of in the root (where the `app` folder, `data` folder, and others are located).

2021-11-25 02:41 UTC, LaoshuBaby commented
![图片](https://user-images.githubusercontent.com/42690037/143369517-eef76823-55a7-4fd1-9ad8-0d6b1a31e1fa.png)

Hey! you need to move it to /data/brands/amenity folder

If you don't know how to do, you can see this commit https://github.com/osmlab/name-suggestion-index/commit/6c968aa28a50cae5e6ee2dfc14fb4bc0aa9a112a .

2021-11-25 02:43 UTC, LaoshuBaby commented
Besides, according to the text diff, you've add 3 brands:

+ Baguette & Baguette
+ Echemi
+ Plan B

If you don't add a wikidata in those entry, they will not be suggested by iD/RapiD automatically.

2021-11-25 02:43 UTC, arch0345 commented
Thanks for the quick fix @LaoshuBaby! This PR looks good, just note that these will not be generated as a preset in iD without a `brand:wikidata` tag

2021-11-25 02:51 UTC, arch0345 requested changes
The fast food brands should be moved from restaurant.json to fast_food.json

2021-11-25 02:51 UTC, arch0345 commented on data/brands/amenity/restaurant.json
> +        "amenity": "fast_food",
```suggestion
        "amenity": "fast_food",
```
This should probably go in `fast_food.json` instead

2021-11-25 02:51 UTC, arch0345 commented on data/brands/amenity/restaurant.json
> +        "amenity": "fast_food",
Same thing applies here

2021-11-25 05:56 UTC, eddy-dardour commented
Alright I'll do the following changes

2021-11-25 06:53 UTC, closed without merging

2021-11-25 07:01 UTC, LaoshuBaby commented
> * Baguette & Baguette
> 
> * Echemi

Those 2 was added in #5733 

（Maybe because “Plan B” haven‘t got a wikidata item yet. You can try to create one if you like.）

Thank you for making your first contribution to NSI ♥