Add Skuratov Сoffee
osmlab/name-suggestion-index pull request #5771
Opened 2021-12-01 13:51 UTC by afanasovich

2021-12-01 17:49 UTC, arch0345 requested changes
The Wikidata page linked doesn't seem to match the brand

2021-12-01 17:49 UTC, arch0345 commented on data/brands/amenity/cafe.json
> +        "brand:wikidata": "Q30891188",
This looks like the wikidata page for Шоколадница, maybe this is a copy-paste mistake?

2021-12-02 08:01 UTC, afanasovich commented on data/brands/amenity/cafe.json
> +        "brand:wikidata": "Q30891188",
Thx.

I made a mistake when I copied the template from Шоколадница. 

Скуратов кофе — Q98642885 https://wikidata.org/wiki/Q98642885

2021-12-02 17:19 UTC, arch0345 approved these changes
Thanks for the quick fix!

2021-12-02 17:19 UTC, merged