Added tags for Lyft/Motivate bikeshare systems
osmlab/name-suggestion-index pull request #5932
Opened 2021-12-25 21:38 UTC by PierceWHoward

I added tags to bikesharing systems owned and operated by Lyft/Motivate to make adding stations/docks easier.

2021-12-25 22:01 UTC, arch0345 requested changes
Thanks @PierceWHoward and welcome! I've left you some suggestions that should be reviewed before merging

2021-12-25 22:47 UTC, PierceWHoward commented on data/brands/amenity/bicycle_rental.json
> +      "displayName": "Lyft Bike",
Would it be okay if I add geojason files and use them?

2021-12-26 00:01 UTC, PierceWHoward commented
I know that the new geojsons aren't that great but I wanted to make sure I included the entire area where locations were possible. Feel free to edit them in the future. :)

2021-12-26 00:10 UTC, arch0345 commented
Looks good! Could you also remove the website and phone tags?

2021-12-26 00:15 UTC, arch0345 commented
Since both Lyft Bikes have the same tags, I would just combine this into one entry that includes both the LA and CO geojsons in the locationSet

2021-12-26 01:20 UTC, PierceWHoward commented
> Since both Lyft Bikes have the same tags, I would just combine this into one entry that includes both the LA and CO geojsons in the locationSet

Oops. My bad the reason I separated them initially was because of the different web addresses. Just pushed the change.

2021-12-26 01:24 UTC, arch0345 approved these changes

2021-12-26 01:25 UTC, merged

2021-12-26 01:31 UTC, PierceWHoward commented
@arch0345 Should I remove opening_hours tags? Do you want me to make any additional changes?

2021-12-26 02:01 UTC, arch0345 commented
Don't worry, I removed it in the commit linked above. No other changes are needed - thanks for your first contribution!