Update cinema.json
osmlab/name-suggestion-index pull request #5993
Opened 2022-01-04 04:32 UTC by dan13l9

I made a few small corrections and additions. Can i add new brands with this method? Thank you.

2022-01-04 04:46 UTC, arch0345 requested changes
Thanks and welcome! I've left some suggestions that should be reviewed before this is merged.

2022-01-04 04:46 UTC, arch0345 commented on data/brands/amenity/cinema.json
> +      "displayName":",
Looks like you accidentally removed the displayName from AMC
```suggestion
      "displayName": "AMC",
```

2022-01-04 04:46 UTC, arch0345 commented on data/brands/amenity/cinema.json
> +        "operator": "Cineworld"
Their Wikipedia article suggests that Cineworld is just the parent company and that Cinema City operates the cinemas
```suggestion
```

2022-01-04 04:46 UTC, arch0345 commented on data/brands/amenity/cinema.json
> +        "operator: "Kinepolis",
I think you mixed [Landmark Theatres](https://en.wikipedia.org/wiki/Landmark_Theatres) with [Landmark Cinemas](https://en.wikipedia.org/wiki/Landmark_Cinemas). It looks like Landmark Cinemas isn't in NSI yet so feel free to add it
```suggestion
```

2022-01-04 05:53 UTC, LaoshuBaby requested changes

2022-01-04 05:53 UTC, LaoshuBaby commented on data/brands/amenity/cinema.json
> +        "include": ["bg, "cz", "hu", "pl", "ro", "sk"]
```suggestion
        "include": ["bg", "cz", "hu", "pl", "ro", "sk"]
```

2022-01-18 17:35 UTC, arch0345 requested changes

2022-01-18 17:35 UTC, arch0345 commented on data/brands/amenity/cinema.json
> +      "locationSet": {"include": ["ro, "sk"]},
```suggestion
      "locationSet": {"include": ["ro", "sk"]},
```

2022-01-18 17:41 UTC, arch0345 requested changes

2022-01-18 17:41 UTC, arch0345 commented on data/brands/amenity/cinema.json
> +        "operator": "Vue Cinemas"
```suggestion
        "operator": "Vue Cinemas",
```

2022-01-18 17:43 UTC, merged