Added TRAM Metropolità d'Alcant
osmlab/name-suggestion-index pull request #6257
Opened 2022-03-03 17:00 UTC by paunofu

Hi, I have added the operator and network tags for the routes managed by the goverment company in the province of Alacant, Spain. It’s my first commit, I hope I don’t have many mistakes :)

2022-03-03 17:06 UTC, LaoshuBaby commented on data/transit/route/light_rail.json
> +        },
```suggestion
          }
        },
```

2022-03-03 17:12 UTC, LaoshuBaby commented on data/transit/route/subway.json
> +        },
```suggestion 
     }  
   },
```

2022-03-03 17:14 UTC, LaoshuBaby commented on data/transit/route/train.json
> +        },
```suggestion
       }
     },
```

2022-03-03 17:15 UTC, LaoshuBaby commented on data/transit/route/tram.json
> +        },
```suggestion
       }
    },
```

2022-03-03 17:46 UTC, LaoshuBaby commented
Hello, friends! Welcome to NSI.

I just fix the typo error in json, and look the wikipedia, looks like there are only tram and train operated by Alicante TRAM, is it really need to create in subway and light_rail ?
![Screenshot_2022-03-04-01-38-31-536_mark via](https://user-images.githubusercontent.com/42690037/156621844-dd1b95a5-a7da-48c4-b4ff-2daae1d039d0.jpg)

2022-03-03 20:57 UTC, paunofu commented
The wikipedia is a bit outdated, the L9 is officially a train, but on ground is a light train and the L4 is a tram and L2 a metro. And you are right, I have just checked and in Barcelona they also use tram.

2022-03-04 10:43 UTC, paunofu commented
It could a possibility change the ISO of the country (ES) for the ISO of the province (ES-A)?

Because the 90% use only TRAM instead of another denomination.

2022-03-04 14:06 UTC, LaoshuBaby commented
> It could a possibility change the ISO of the country (ES) for the ISO of the province (ES-A)?

Sorry, location-conflation didn't support this currently.

![图片](https://user-images.githubusercontent.com/42690037/156776134-56d3fcc2-4c83-4bec-a159-32f397aea984.png)

Only those area have a geojson can use provincial name, such as `us-mi.geojson`, you can see them in this folder:

https://github.com/osmlab/name-suggestion-index/tree/main/features/us

![图片](https://user-images.githubusercontent.com/42690037/156776778-744340f9-02a1-4d6b-a3c8-22fcc6c83da3.png)

---

But don't worry, you can use a circle region and add a note to tell other where the region affect:

![图片](https://user-images.githubusercontent.com/42690037/156777224-7140486a-073f-4156-89db-8cd17554baef.png)

(You can have a try at: https://location-conflation.com/?locationSet=%7B%20include%3A%20%5B%5B-0.4881%2C%2038.3436%2C%2025%5D%5D%20%7D)

2022-03-04 14:33 UTC, paunofu commented
I have the geojson of three regions of Spain, one of them the region that I want, I can upload it to features.

2022-03-04 16:16 UTC, arch0345 requested changes
Thanks for adding these geojsons, however, NSI [only supports](https://github.com/osmlab/name-suggestion-index/wiki/Feature-Files) a single geojson `Feature` (or a FeatureCollection containing a single `Feature`) and `Polygon` or `MultiPolygon` geometries. I recommend creating these by hand instead with geojson.io using the polygon tool as suggested in the wiki article linked above. We try to use as few points as possible, see https://github.com/osmlab/name-suggestion-index/issues/4784#issuecomment-742003434. It looks like others use less than 100 points.

2022-04-04 01:36 UTC, arch0345 approved these changes
Thanks for your patience @paunofu! This looks good to me

2022-04-04 01:36 UTC, merged