Add operator social_facility : Club Alpino Italiano [resolves #6971]
osmlab/name-suggestion-index pull request #7181
Opened 2022-10-12 19:47 UTC by Tck13

The Club Alpino Italiano is the senior Italian alpine club which stages climbing competitions, operates alpine huts, marks and maintains paths, and is active in protecting the Alpine environment. https://en.wikipedia.org/wiki/Club_Alpino_Italiano

2022-10-12 19:55 UTC, arch0345 requested changes

2022-10-12 19:55 UTC, arch0345 commented on data/operators/amenity/social_facility.json
> +        "operator:wikipedia": "it:Club Alpino Italiano"
```suggestion
```
All `:wikipedia` tags were removed from NSI in #6481

2022-10-12 22:13 UTC, Tck13 commented
Thanks for the link to the update, I didn't know that.  I had still looked at the wiki because of whether it could be an Italian wikipedia page 😅

I will soon make a separate pull request to update the wiki pages regarding the mentioned change (#6481)

2022-10-13 05:38 UTC, arch0345 approved these changes

2022-10-13 05:38 UTC, merged