Polish pharmacies - remove duplicates
osmlab/name-suggestion-index pull request #7451
Opened 2022-11-24 07:42 UTC by mutipg

### id_to_remove > as_duplicate_of_id
aptekagemini-cf61fb > gemini-cf61fb
aptekarodzinna-cf61fb > rodzinna-cf61fb
aptekasloneczna-cf61fb > sloneczna-cf61fb

2022-11-24 08:16 UTC, LaoshuBaby requested changes

2022-11-24 08:16 UTC, LaoshuBaby commented on data/brands/amenity/pharmacy.json
> -      "locationSet": {"include": ["pl"]},
There are still a lot elements in OSM named after this according to taginfo, also "Apteka Rodzinna" and "Apteka Słoneczna"

![图片](https://user-images.githubusercontent.com/42690037/203727754-563f10fb-f184-4eba-bbd3-55baad732f16.png)

So if you only removed those 3 entry, they will be created once again, our collector will found they are still "widely used" in real world.

If this change is from business merge or rebrand, or bought by another brand, I'd suggest you add a `"matchNames": ["Apteka Gemini"],` in your targeted `gemini-cf61fb`, another 2 also need this.

For example, "頂好超市" was bought by "家樂福超市":

https://github.com/osmlab/name-suggestion-index/blob/f57288c32f5fb2de87fc6c8bc5943ba818bf403b/data/brands/shop/supermarket.json#L9696-L9701

2022-12-03 11:43 UTC, kjonosm commented
@matkoniecz You seem to have a good overview of the Polish tagging preferences. Which version do you think we should keep/promote in NSI?

2022-12-03 13:09 UTC, matkoniecz commented
here I am not really sure, so created https://community.openstreetmap.org/t/sloneczna-czy-apteka-sloneczna/6296

2023-02-05 08:35 UTC, Dimitar5555 commented
@matkoniecz Is there any result from the discussion on the forum? If there isn't, it may be beneficial to create a poll and see if there is a majority which prefers one of the options.

2023-02-06 11:30 UTC, matkoniecz commented
Skipping "apteka" ("pharmacy") in name seems preferred but it is not unanimous.

2024-05-25 16:56 UTC, bhousel commented
stale

2024-05-25 16:56 UTC, closed without merging