Add Xarxa de Casals i Ateneus dels PPCC
osmlab/name-suggestion-index pull request #8281
Opened 2023-06-16 20:57 UTC by jmaspons

2023-06-17 04:08 UTC, LaoshuBaby commented on data/brands/amenity/social_centre.json
> +        "network:website": "https://www.casalsiateneus.cat"
> Each item requires a tags value. This is just an Object containing all the OpenStreetMap tags that should be set on the feature.
>
> Note for brands, that common tags with additional details such as "website" or "facebook" is not accepted directly. Instead a tag referencing the brand's [wikidata](https://www.wikidata.org/) entry ("[brand:wikidata](https://wiki.openstreetmap.org/wiki/Key:brand:wikidata)") containing those details can be included. If no such exists, consider [adding it](https://www.wikidata.org/wiki/Special:NewItem).

https://github.com/osmlab/name-suggestion-index/wiki/Contributing#tags-required

2023-09-28 14:28 UTC, bhousel commented
This won't work without the `amenity=social_centre` tag

2023-10-25 09:42 UTC, Robot8A requested changes
A trailing "s" is missing at the network name: Catalan**s**

Should the .geojson be inside the subfolder "ppcc"?

2024-05-25 16:52 UTC, bhousel commented
closing as there's still issues with this missing tags

2024-05-25 16:52 UTC, closed without merging