Add German American Bank
osmlab/name-suggestion-index pull request #8425
Opened 2023-07-21 16:18 UTC by DivyaB1

Hi,
I'm adding 'German American Bank' - https://germanamerican.com/personal/

2023-07-21 16:32 UTC, bhousel requested changes
Thanks!  What do you think of using the simpler name?  Their branding doesn't seem to include the word "Bank"

2023-07-21 16:32 UTC, bhousel commented on data/brands/amenity/bank.json
> +        "brand": "German American Bank",
```suggestion
        "brand": "German American",
```
Based on their branding, I would just call it "German American" in both the `brand` and `displayName` props.

<img width="300" alt="Screenshot 2023-07-21 at 12 30 07 PM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/5ec740c0-da41-440f-afa9-6db478db9c1b">

2023-07-21 16:32 UTC, bhousel commented on data/brands/amenity/bank.json
> +      "displayName": "German American Bank",
```suggestion
      "displayName": "German American",
```

2023-07-21 21:24 UTC, DivyaB1 commented
Hi,
Thanks, they referred themselves as 'German American Bank' in their 'About Us' page so I added it. I've corrected it now!
https://germanamerican.com/about/history/#:~:text=The%20history%20of-,German%20American%20Bank,-tells%20quite%20an

2023-07-24 13:49 UTC, bhousel commented
Thanks @DivyaB1 👍

2023-07-24 13:49 UTC, bhousel approved these changes

2023-07-24 13:49 UTC, merged