Add Vychodoslovenska distribucna as new line operator
osmlab/name-suggestion-index pull request #8899
Opened 2023-11-02 20:03 UTC by luky89

Hi It is my first PR in name-suggestion-index project. Could you please check it?
I would like add Vychodoslovenska distribucna company between power operators. Vychodoslovenska distribucna is between substation power operators but it miss in line operators (i can't create line, pole owned by Vychodoslovenska distribucna).

Thank you

2023-11-03 23:34 UTC, AntiCompositeNumber requested changes
Welcome! This change looks good, just the `power` tag needs to be fixed.

2023-11-03 23:34 UTC, AntiCompositeNumber commented on data/operators/power/line.json
> +        "power": "substation"
```suggestion
        "power": "line"
```
The `power` tag needs to match

2023-11-04 18:37 UTC, luky89 commented on data/operators/power/line.json
> +        "power": "substation"
updated

2023-11-04 18:39 UTC, AntiCompositeNumber approved these changes

2023-11-04 18:40 UTC, merged