Add Johnson Fitness & Wellness
osmlab/name-suggestion-index pull request #8919
Opened 2023-11-08 19:00 UTC by molliemchugh-tomtom

Hello,

I'm adding Johnson Fitness & Wellness.

https://www.johnsonfitness.com/

2023-11-08 19:42 UTC, AntiCompositeNumber commented on data/brands/shop/sports.json
> +        "shop": "sports"
```suggestion
        "shop": "sports",
        "sport": "fitness"
```
Based on their website, I think it makes sense to add [`sport=fitness`](https://wiki.openstreetmap.org/wiki/Tag%3Asport%3Dfitness)

2023-11-08 21:04 UTC, molliemchugh-tomtom commented
Hello @AntiCompositeNumber,

This company sells sports equipment.  It is not a fitness center or gym.

I think it should be left as is.

2023-11-09 15:31 UTC, AntiCompositeNumber commented
`sport=` is commonly used to specify the type of equipment a `shop=sports` sells. I'm not particularly opposed to leaving it out, but I do think it would be useful to include.

2023-11-09 20:04 UTC, molliemchugh-tomtom commented
My understanding is that sports=fitness is for locations where people use sports equipment to improve their health/fitness.

https://wiki.openstreetmap.org/wiki/Tag%3Asport%3Dfitness#:~:text=The%20tag%20sport%3Dfitness%20is%20commonly%20added%20to%20features%20such%20as%20leisure%3Dfitness_centre%20or%20leisure%3Dfitness_station%20where%20people%20develop%20physical%20fitness%20by%20group%20classes%2C%20cardio%20machines%2C%20weight%20lifting%2C%20and%20related%20activities

This business is a place where sports equipment/workout machines **are sold** .  It is not a club, center, or location for using sports equipment.

However, if you insist on changing this to shop=fitness, I will do so.

2023-11-09 20:52 UTC, AntiCompositeNumber requested changes
Looking at https://overpass-turbo.eu/s/1Dc7, looks like there's 2 stores with `sport=fitness`, but I'm fine leaving that out.

There are a bunch of stores tagged `leisure=fitness_centre` `name=Johnson Fitness & Wellness Store` so matchNames and matchTags should be added for those.

2023-11-09 20:52 UTC, AntiCompositeNumber commented on data/brands/shop/sports.json
> +      },
```suggestion
      },
      "matchNames": ["johnson fitness & wellness store"],
      "matchTags": ["leisure/fitness_centre"],
```

2023-11-09 21:56 UTC, AntiCompositeNumber approved these changes

2023-11-09 21:56 UTC, merged

2023-11-09 21:58 UTC, Cj-Malone commented
Thanks everyone