Add and edit companies found in Australia and the world
osmlab/name-suggestion-index pull request #8925
Opened 2023-11-09 22:54 UTC by Scottie0001

Add new companies found in Australia and the world, edit Cotton On to edit name in OSM.

2023-11-10 00:05 UTC, Cj-Malone commented on data/brands/shop/bag.json
> +        "brand:wikidata": "Q1203Q111946652426",
Presumably this is an error

2023-11-10 00:07 UTC, AntiCompositeNumber commented on data/brands/shop/bag.json
> +        "brand:wikidata": "Q1203Q111946652426",
```suggestion
        "brand:wikidata": "Q111946652",
```
appears to be the correct one

2023-11-10 01:23 UTC, Scottie0001 commented on data/brands/shop/bag.json
> +        "brand:wikidata": "Q1203Q111946652426",
That is correct, wikidata is Q111946652

2023-11-10 05:00 UTC, AntiCompositeNumber requested changes
In general, `brand=`, `name=`, and the NSI `displayName` should all match unless there's a good reason for them not to. All should use OSM naming conventions, which may not match what is used on Wikidata or Wikipedia. Be careful that the locationSet value(s) you choose are correct.

In the future, smaller, more focused pull requests are easier to review.

2023-11-10 06:42 UTC, Scottie0001 commented on data/brands/shop/clothes.json
> +      "preserveTags": ["^name"],
There are multiple brands of stores that Cotton On have that do not have a wikidata

2023-11-10 06:44 UTC, Scottie0001 commented on data/brands/shop/bed.json
> +        "brand:wikidata": "Q123014288",
Edited to reflect US stores, no wikidata tag for Australian company

2023-11-10 06:45 UTC, Scottie0001 commented on data/brands/office/insurance.json
> +      "displayName": "RACQ",
Names to reflex more general traffic

2023-11-10 06:49 UTC, Scottie0001 commented
Changes have been made to reflect suggestions

2023-11-11 03:45 UTC, AntiCompositeNumber commented on data/brands/office/insurance.json
> +      "displayName": "RACQ",
I'm not sure what you mean.

2023-11-11 04:02 UTC, Scottie0001 commented on data/brands/office/insurance.json
> +      "displayName": "RACQ",
I have updated the name/brand to reflect the business name and suggestions. Previous comment was a typo mistake.

2023-11-11 04:18 UTC, AntiCompositeNumber approved these changes

2023-11-11 04:19 UTC, merged