Add more POIs in Canada
osmlab/name-suggestion-index pull request #8932
Opened 2023-11-12 00:33 UTC by andrewpmk

Added POIs:
- Access Storage
- Active Green + Ross
- Ali Baba's
- Becker's
- Big Bear/Big Bee
- Bikini Village
- BioPed
- Blinds to Go
- Bouclair Home
- Bourbon St. Grill
- BrokerLink
- Burrito Boyz
- Maison Birks
- Mister Transmission
- Mobile Klinik
- Moxie's
- Quickie
- Sirens
- South Street Burger
- Stinson
- Sun Life Financial
- The Works
- Trade Secrets
Updated POIs:
- 9Round
- Allstate
- Alterna Savings
- Boathouse
- Nails For You

2023-11-16 01:36 UTC, AntiCompositeNumber requested changes
In the future, smaller, more focused pull requests are easier to review.

2023-11-16 01:36 UTC, AntiCompositeNumber commented on data/brands/shop/window_blind.json
> +      "locationSet": {"include": ["ca"]},
```suggestion
      "locationSet": {"include": ["ca-on.geojson", "us-ct.geojson", "us-de.geojson", "us-ma.geojson", "us-md.geojson", "us-nj.geojson", "us-ny.geojson", "us-pa.geojson", "us-va.geojson"]},
```
per https://www.blindstogo.com/en/stores

2023-11-16 01:36 UTC, AntiCompositeNumber commented on data/brands/shop/window_blind.json
> +      "locationSet": {"include": ["ca"]},
Please also add an entry for Quebec per https://www.blindstogo.com/fr/magasins

2023-11-16 08:24 UTC, Cj-Malone commented on data/brands/shop/interior_decoration.json
> +    },
In theory `name` should be the [facia](https://www.google.com/maps/place/Bouclair+Home/@43.841389,-79.4211637,3a,75y,350.68h,93.34t/data=!3m7!1e1!3m5!1sTsTvVsXs7ve9J7Ix9ZEj2Q!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DTsTvVsXs7ve9J7Ix9ZEj2Q%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D341.89697%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192!4m10!1m2!2m1!1sBouclair+Home!3m6!1s0x882b2b836f0272ff:0x1bbb23ec256ca6e4!8m2!3d43.8415112!4d-79.4212305!15sCg1Cb3VjbGFpciBIb21lIgOIAQFaDyINYm91Y2xhaXIgaG9tZZIBD2Z1cm5pdHVyZV9zdG9yZeABAA!16s%2Fg%2F1tjl6jt0?entry=ttu) and `brand` the ["brand"](https://www.bouclair.com/en/).

However OSM and NSI aren't prefect in this.

2023-11-16 22:30 UTC, andrewpmk commented on data/brands/shop/convenience.json
> +        "brand:wikidata": "Q123409887",
Looks like they are separate chains https://www.reddit.com/r/Hamilton/comments/4bw8rt/big_bear_vs_big_bee_stores/
They're chains of convenience stores near Hamilton Ontario (also Niagara Falls, St Catharines, Kitchener etc.)

2023-11-16 22:32 UTC, andrewpmk commented on data/brands/shop/interior_decoration.json
> +    },
They're different brands of store operated by the same company. NSI keeps asking me to change "Bouclair Home" stores to "Bouclair" which is incorrect.
We have the same issue with "The Brick" vs "The Brick Mattress Store".

2023-11-16 22:45 UTC, andrewpmk commented on data/brands/leisure/fitness_centre.json
> +        "include": [
Changed to 001

2023-11-16 22:46 UTC, andrewpmk commented on data/brands/shop/convenience.json
> +        "brand:wikidata": "Q123409887",
Removed Big Bear. Looks like it is not the same chain https://www.reddit.com/r/Hamilton/comments/4bw8rt/big_bear_vs_big_bee_stores/

2023-11-16 22:46 UTC, andrewpmk commented on data/brands/shop/interior_decoration.json
> +    },
Added French entry

2023-11-16 22:49 UTC, andrewpmk commented
Updated pull request with suggested changes.
Removed Big Bear because it appears to be different from Big Bee.
Added French entries for Bouclair Home and Blinds to Go.

2023-11-17 19:09 UTC, AntiCompositeNumber requested changes

2023-11-17 19:09 UTC, AntiCompositeNumber commented on data/brands/shop/window_blind.json
> +        "brand:wikidata": "Q113686682",
```suggestion
        "brand:wikidata": "Q123409913",
```

2023-11-17 19:21 UTC, AntiCompositeNumber approved these changes

2023-11-17 19:21 UTC, andrewpmk commented
Updated brand:wikidata of Blinds to Go to Q123409913

2023-11-17 19:22 UTC, merged